num_episodes: 15000
save_ratio: 500
batch_size: 128
gamma: 0.99
eps_start: 1.0
eps_end: 0.05
eps_decay: 20000
target_update: 1000
learning_rate: 1e-4
horizon: 100
tau: 0.005
print_ratio: 100
save_model: False
use_fta: True
soft_target_update: True
use_aux: "ir"