num_episodes: 7500
save_ratio: 500
batch_size: 128
gamma: 0.99
eps_start: 0.9
eps_end: 0.05
eps_decay: 10000
target_update: 1000
learning_rate: 1e-4
horizon: 100
tau: 0.005
print_ratio: 100
save_model: True
use_fta: True
soft_target_update: True
# use_aux: "no_aux", "ir", "reward", "sf"
use_aux: "sf+reward"
# goal_mode: {0: default goal, 1: similar task, 2: more dificult task}
goal_mode: 1
model_path: "/home/arya/arya/rl/investigate-representations-drl/.models/sf_reward_model.pt"
