runs: 3
max_episodes: 15000
transfer: True
save_ratio: 500
plot_during_training: False
batch_size: 128
gamma: 0.99
eps_start: 1.0
eps_end: 0.05
eps_decay: 20000
target_update: 1000
learning_rate: 1e-3
horizon: 100
tau: 0.001
print_ratio: 100
save_model: False
use_fta: True
soft_target_update: True
save_rewards: True
# use_aux: "no_aux", "ir", "reward", "sf", "virtual-reward-1", "virtual-reward-5"
use_aux: "ir"

goal_mode: 2
# finish the training after number of consecutive episodes with reward of 1
consecutive_episodes: 100
model_path: ".models/fta/ir/pytorch_2023-08-10_09:41.pt"
